routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', 'Auth\LoginController@loginForm');*/

Auth::routes();
// Route::get('/dd', function () {
//     $img = Image::make(public_path('uploads/ads/s.jpeg')); //1000000

//     return $img->filesize();
// });
Route::get('/', function () {
    return redirect(route('admin.halls.index'));
})->name('home');
Route::get('/home', function () {
    return redirect(route('admin.halls.favorite'));
});

Route::group( [ 'prefix' => 'admin' , 'namespace' => 'admin' , 'as' => 'admin.'], function()
{
    Route::get('/halls/get/pendings/ajax', 'HallController@getPendigHallsAjax')->name('get.pending.halls.ajax');
    Route::group( ['middleware' => ['auth']], function() {
        Route::view('/dashboard', 'admin/dashboard')->name('dashboard');
        Route::post('/halls/rate/hall', 'HallController@rateHall')->name('halls.rate');
        Route::post('/halls/rate/active/{id}', 'HallController@activeHall')->name('halls.active');
        Route::post('/halls/rate/note', 'HallController@rateNote')->name('rate.note');
        Route::get('/halls/reservations/{id}', 'HallController@reservations')->name('halls.reservations');
        Route::get('/halls/get/pendings', 'HallController@pendingHalls')->name('get.pending.halls');
        Route::get('/halls/list', 'HallController@listHalls')->name('halls.list');
        Route::resource('/roles', 'RoleController');
        Route::resource('/users', 'UserController');
        Route::get('/users/search/all', 'UserController@search')->name('search.user');
        Route::post('/users/status', 'UserController@changeStatus')->name('users.status');
        Route::get('/profile/edit', 'UserController@editProfile')->name('profile.edit');
        Route::put('/profile/update', 'UserController@updateProfile')->name('profile.update');
        Route::get('/user/get/reservations', 'UserController@getReservations')->name('user.reservations');
        Route::resource('/categories', 'CategoryController');
        Route::get('/categories/extra/get', 'CategoryController@getExtra')->name('categories.extra');
        Route::resource('/category_extras', 'CategoryExtraController');
        Route::resource('/cities', 'CityController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/reservations', 'ReservationController');
        Route::post('/reservations/cancel/{id}', 'ReservationController@cancelReservation')->name('reservations.cancel');
        Route::post('/reservations/status/{id}', 'ReservationController@reservationStatus')->name('reservations.status');
        Route::resource('/media', 'HallMediaController');
        Route::resource('/inquiries', 'InquiryController');
        Route::resource('/ads', 'AdsController');
        Route::resource('/prices', 'HallPriceController');
        Route::post('/prices/sort/hall', 'HallPriceController@sortPrices')->name('prices.sort');
        Route::get('/halls/search', 'HallController@search')->name('halls.search');
        Route::get('/calendar', 'CalendarController@index')->name('calendar.index');

        Route::post('calendar/get/events','CalendarController@getEvents')->name('get.events');
        Route::post('calendar/create','CalendarController@create')->name('event.add');
        Route::post('calendar/resize','CalendarController@resize')->name('event.resize');
        Route::post('calendar/update','CalendarController@update')->name('event.update');
        Route::post('calendar/delete','CalendarController@destroy')->name('event.destroy');


        Route::get('/notifications','NotificationController@getNew')->name('notifications.new');


        Route::resource('/alerts','AlertController');
        Route::post('/alert/send','AlertController@send')->name('alerts.send');

        Route::get('/hall/add/favorite/{id}', 'HallController@addFavorite')->name('hall.add.favorite');
        Route::get('/hall/remove/favorite/{id}', 'HallController@removeFavorite')->name('hall.remove.favorite');
        Route::get('/hall/favorite/show', 'HallController@favorite')->name('halls.favorite');
        Route::get('/halls/get/favorite', 'HallController@getFavorite')->name('halls.get.favorite');
        Route::post('/hall/get/reserved', 'HallController@getHallReserved')->name('hall.reserved');
        Route::get('/myHalls', 'HallController@getMyHalls');
    });
    Route::get('/halls/get/maps', 'HallController@hallsOnMap')->name('get.halls.map');

    Route::resource('/halls', 'HallController');
    Route::get('/halls/get/ajax', 'HallController@getHallsAjax')->name('get.halls');
    Route::get('/halls/search/all', 'HallController@search')->name('search.hall');
    Route::resource('/partners', 'PartnerController');
    Route::get('/partners/main/{id}', 'PartnerController@main');
    Route::get('/partners/getSalesMen/{id}', 'PartnerController@getSalesMen');

    Route::get('/partners/branches/{id}', 'PartnerController@branches');
    Route::post('/partners/addBranch', 'PartnerController@addBranch');
    Route::post('/partners/updateBranch', 'PartnerController@updateBranch');
    Route::get('/partners/coupons/{id}', 'PartnerController@coupons');
    // Route::get('/partners/coupons/{id}/details', 'PartnerController@couponDetails');
    Route::get('/partners/branch/{id}/details', 'PartnerController@branchDetails');
    Route::post('/partners/product/edit', 'PartnerController@editProduct');
    Route::post('/partners/product/updatediscountPerProduct', 'PartnerController@updatediscountPerProduct');
    Route::post('/partners/product/add', 'PartnerController@addProd');
    Route::post('/partnersCouponeAdd', 'PartnerController@partnersCouponeAdd');
    Route::post('/partners/product/update/existProduct', 'PartnerController@editExistProduct');
    // Route::get('/partners/discount/edit', 'PartnerController@eDiscountType');
    Route::get('/partners/discount/edit', 'PartnerController@edit');
    Route::get('/partners/product/remove/{id}/{p}', 'PartnerController@removeProduct');
    Route::get('/partners/Branch/addNew/{id}', 'PartnerController@addNew');
    Route::get('/partners/Branch/edit/{id}/{b_id}', 'PartnerController@editBranch');
    Route::get('/partners/product/update/{id}/{p}', 'PartnerController@goToEditProductPage');
    Route::get('/partners/salesman/store/', 'PartnerController@addSalesMan');

});

Route::post('/test', 'admin\HallController@store');
Route::get('/user-guide',function () {
    return view('user-guide');
});
Route::get('/contact-us', 'admin\UserController@contact_us');

app/models/Ads.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Ads extends Model
{
    protected $table = 'ads';
    protected $guarded = ["id","image","created_at","updated_at", "hall_id"];
    protected $hidden = ["image_path"];

    public function get_hall()
    {
        if($this->type == "hall")
            return Hall::findOrFail($this->item_id);
        else
            return false;
    }
}

app/Http/Controllers/admin/AdsController.php
<?php

namespace App\Http\Controllers\admin;

use App\models\Ads;
// use App\models\UserActivity;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use Illuminate\Validation\Rule;

class AdsController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $model_instance;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view = 'admin.ads.index';
        $this->create_view = 'admin.ads.create';
        $this->show_view = 'admin.ads.show';
        $this->edit_view = 'admin.ads.edit';
        $this->index_route = 'admin.ads.index';
        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_created_successfully');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
        $this->model_instance = Ads::class;
    }

    private function StoreValidationRules($request)
    {
        return [
            'title' => 'required|string|min:3|max:200',
            'type' => 'required|in:ads,hall',
            // 'item_id' => 'nullable',
            'item_id' => Rule::requiredIf($request->type=="hall"),
            'image' => 'required|mimes:jpg,png,jpeg,gif,svg',
        ];
    }

    private function UpdateValidationRules($request)
    {
        return [
            'title' => 'required|string|min:3|max:200',
            'type' => 'required|in:ads,hall',
            // 'item_id' => 'nullable',
            'item_id' => Rule::requiredIf($request->type=="hall"),
            'image' => 'sometimes|mimes:jpg,png,jpeg,gif,svg',
        ];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $ads = $this->model_instance::all();
        return view($this->index_view, compact('ads'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        has_access('ads_create');
        return view($this->create_view);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        has_access('ads_create');
        $validated_data = $request->validate($this->StoreValidationRules($request));
//dd($validated_data);
        try {

            $object = $this->model_instance::create($validated_data);
            if($request->hasFile('image'))
            {

                $image_data = hl_uploadFileTo($validated_data["image"],'ads');
                $object->image_url = $image_data["media_url"];
                $object->image_path = $image_data["media_path"];
                $object->update();
            }

            $log_message = trans('ads.create_log') . '#' . $object->id;
            return redirect()->route($this->index_route)->with('success', $this->success_message);
        } catch (\Exception $ex) {
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        $category = $this->model_instance::findOrFail($id);
        return view($this->show_view, compact('category'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        has_access('ads_update');
        $ads = $this->model_instance::findOrFail($id);

        return view($this->edit_view, compact(['ads']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        has_access('ads_update');
        $validated_data = $request->validate($this->UpdateValidationRules($request));

        try {
            $object = $this->model_instance::find($id);
            //dd($validated_data);
            $updated_instance = $object->update($validated_data);

            if($request->hasFile('image'))
            {

                $image_data = hl_uploadFileTo($validated_data["image"],'ads');
                hl_deleteFile($object->image_path);
                $object->image_url = $image_data["media_url"];
                $object->image_path = $image_data["media_path"];
                $object->update();
            }


            $log_message = trans('ads.update_log') . '#' . $object->id;
           // UserActivity::logActivity($log_message);

            if ($updated_instance) {
                return redirect()->route($this->index_route)->with('success', $this->update_success_message);
            } else {
                return redirect()->route($this->index_route)->with('error', $this->update_error_message);
            }



        } catch (\Exception $ex) {
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        has_access('ads_remover');

        if ($request->ajax()) {
            $deleted = $this->model_instance::findOrFail($id)->delete();
            if ($deleted) {
                $log_message = trans('ads.delete_log') . '#' . $id;
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }




        }

        return redirect()->route($this->index_route);
    }
}

app/Http/Controllers/api/AdsController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Resources\Hall as HallResource;
use App\models\Ads;
use App\models\Hall;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class AdsController extends Controller
{
    public function index()
    {
        $ads = Ads::all()->toArray();

        foreach ($ads as $key =>$ad)
        {
            if($ad["type"] == "hall")
            {
                $ads[$key]["hall"] = new HallResource(Hall::findOrFail($ad["item_id"]));
            }
            else
            {
                $ads[$key]["hall"] = [];
            }
        }

        return $ads;
    }
}

resources/views/admin/ads/create.blade.php
@extends('layouts.app')

@section('title',trans('ads.create'))


@section('styles')

    <style>
        .wrapper-pic {
            position: relative;
            display: inline-block;
            opacity: 1;
        }

        .wrapper-pic:hover {
            transition: all .2s ease-in-out;
        }

        .wrapper-pic:hover .edit {
            transition: all .2s ease-in-out;
            display: block;
        }

        .edit {
            padding-top: 7px;
            padding-right: 7px;
            position: absolute;
            left: 20px;
            top: 10px;
            display: none;
        }
    </style>

@endsection

@section('content')


    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                @include('flash-message')
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">@lang('ads.create')</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.ads.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-8">


                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.title')</label>

                                <div class="col-md-10">
                                    <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" required autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.type')</label>

                                <div class="col-md-10">
                                    <select name="type" class="form-control" onchange="get_item_data(event)">
                                        <option value="ads" selected>@lang('ads.ads')</option>
                                        <option value="hall" >اعلان عن قاعة</option>
                                         
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row" id="adForId" style="display: none">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.item')</label>

                                <div class="col-md-10">
                                    <select class="form-control" id="ads_item" name="item_id">

                                    </select>
                                    <span style="color: red;font-family: monospace;font-size: inherit;">*Required</span>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.image')</label>

                                <div class="col-md-10">
                                    <input type="file" name="image" class="form-control">
                                </div>
                            </div>

                                    <input type="hidden" id="selected_item" name="hall_id">


                            <div class="form-group row mb-0">
                                <div class="col-md-12 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                       @lang('admin.create')
                                    </button>

                                </div>
                            </div>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('scripts')
    <script>
        function enableHallsSearching() {
            var searchUrl = '{{ route('admin.halls.search') }}';
            searchingFor(searchUrl);
            attachHall();


        }

        function attachHall(){
            $('#ads_item').off('select2:select').on('select2:select', function (event) {
                var id = $(event.currentTarget).find("option:selected").val();
                if(confirm('@lang('admin.sure_to_add_category')'))
                {
                    $('#selected_item').attr('value',id);
                }
            });
        }

        function searchingFor(url)
        {
            //console.log(url);
            if(url === '')
            {
                return;
            }
            $('#ads_item').empty();
            $('#ads_item').select2({
                placeholder: "@lang('admin.type_search_word')",
                minimumInputLength: 2,
                ajax: {
                    url: url,
                    dataType: 'json',
                    data: function (params) {
                        return {
                            q: $.trim(params.term)
                        };
                    },
                    processResults: function (data) {
                      //  console.log(data);
                        return {
                            results: data
                        };
                    },
                    error: function (err) {
                        console.log(err);
                    },
                    cache: true
                }
            });
        }

       function get_item_data(event)
        {
            var selected_value  = $(event.target).val();
            if(selected_value === "hall"){
                enableHallsSearching();
                // $('#adForId').removeAttr('hidden');
                $("#adForId").css("display", "flex");
                
                }
            else if(selected_value === "ads")
            {
                $("#adForId").css("display", "none");
                $('#ads_item').empty();
                var ele = `<option value="">اعلان مجرد</option>`;
                $('#ads_item').append(ele);
            }
        }

        enableHallsSearching()
    </script>
@endsection

resources/views/admin/ads/edit.blade.php
@extends('layouts.app')

@section('title',trans('ads.edit'))


@section('styles')

    <style>
        .wrapper-pic {
            position: relative;
            display: inline-block;
            opacity: 1;
        }

        .wrapper-pic:hover {
            transition: all .2s ease-in-out;
        }

        .wrapper-pic:hover .edit {
            transition: all .2s ease-in-out;
            display: block;
        }

        .edit {
            padding-top: 7px;
            padding-right: 7px;
            position: absolute;
            left: 20px;
            top: 10px;
            display: none;
        }
    </style>

@endsection

@section('content')


    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                @include('flash-message')
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">@lang('ads.edit')</div>
                    <div class="row">
                        <div class="col-md-8">
                            <div class="card-body">
                                <form method="POST" action="{{ route('admin.ads.update',$ads->id) }}"
                                      enctype="multipart/form-data">
                                    @csrf
                                    @method('PUT')
                                    <div class="form-group row">
                                        <label class="col col-form-label text-md-right">@lang('ads.title')</label>

                                        <div class="col-lg-10 col-md-12">
                                            <input type="text" class="form-control @error('title') is-invalid @enderror"
                                                   name="title" value="{{ $ads->title }}" required autofocus>

                                            @error('title')
                                            <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col col-form-label text-md-right">@lang('ads.type')</label>

                                        <div class="col-lg-10 col-md-12">
                                            <select name="type" class="form-control" onchange="get_item_data(event)">
                                    <option value="hall" {{ $ads->type == "hall" ? "selected" : "" }}>@lang('ads.hall')</option>
                                    <option value="ads" {{ $ads->type == "ads" ? "selected" : "" }}>@lang('ads.ads')</option>
                                            </select> 
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col col-form-label text-md-right">@lang('ads.item')</label>

                                        <div class="col-lg-10 col-md-12">
                                            <select class="form-control" id="ads_item" name="item_id">
                                                <option value="{{ $ads->get_hall()->id }}" selected>{{ $ads->get_hall()->name ?? '' }}</option>
                                            </select>
                                        </div>
                                    </div>

                                    <div class="form-group row">
                                        <label class="col col-form-label text-md-right">@lang('ads.image')</label>

                                        <div class="col-lg-10 col-md-12">
                                            <input type="file" name="image" class="form-control">
                                        </div>
                                    </div>

                                    <input type="hidden" id="selected_item" name="hall_id" value="{{ $ads->get_hall()->id }}">


                                    <div class="form-group row mb-0">
                                        <div class="col-md-12 offset-md-2">
                                            <button type="submit" class="btn btn-primary">
                                                @lang('admin.edit')
                                            </button>

                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>

                        <div class="col-md-3">
                            <img src="{{ getMediaUrl($ads->image_path) }}" class="img-fluid" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

        @endsection


        @section('scripts')
            <script>
                function enableHallsSearching() {
                    var searchUrl = '{{ route('admin.halls.search') }}';
                    searchingFor(searchUrl);
                    attachHall();


                }

                function attachHall(){
                    $('#ads_item').off('select2:select').on('select2:select', function (event) {
                        var id = $(event.currentTarget).find("option:selected").val();
                        if(confirm('@lang('admin.sure_to_add_category')'))
                        {
                            $('#selected_item').attr('value',id);
                        }
                    });
                }

                function searchingFor(url)
                {
                    //console.log(url);
                    if(url === '')
                    {
                        return;
                    }
                    $('#ads_item').empty();
                    $('#ads_item').select2({
                        placeholder: "@lang('admin.type_search_word')",
                        minimumInputLength: 2,
                        ajax: {
                            url: url,
                            dataType: 'json',
                            data: function (params) {
                                return {
                                    q: $.trim(params.term)
                                };
                            },
                            processResults: function (data) {
                                //  console.log(data);
                                return {
                                    results: data
                                };
                            },
                            error: function (err) {
                                console.log(err);
                            },
                            cache: true
                        }
                    });
                }

                function get_item_data(event)
                {
                    var selected_value  = $(event.target).val();
                    if(selected_value === "hall")
                        enableHallsSearching();
                    else if(selected_value === "ads")
                    {
                        $('#ads_item').empty();
                        var ele = `<option value="">اعلان مجرد</option>`;
                        $('#ads_item').append(ele);
                    }
                }



            </script>
@endsection

resources/views/admin/ads/show.blade.php
@extends('layouts.app')

@section('title','')

@section('content')

    <h1>show page</h1>

@endsection