routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', 'Auth\LoginController@loginForm');*/

Auth::routes();
// Route::get('/dd', function () {
//     $img = Image::make(public_path('uploads/ads/s.jpeg')); //1000000

//     return $img->filesize();
// });
Route::get('/', function () {
    return redirect(route('admin.halls.index'));
})->name('home');
Route::get('/home', function () {
    return redirect(route('admin.halls.favorite'));
});

Route::group( [ 'prefix' => 'admin' , 'namespace' => 'admin' , 'as' => 'admin.'], function()
{
    Route::get('/halls/get/pendings/ajax', 'HallController@getPendigHallsAjax')->name('get.pending.halls.ajax');
    Route::group( ['middleware' => ['auth']], function() {
        Route::view('/dashboard', 'admin/dashboard')->name('dashboard');
        Route::post('/halls/rate/hall', 'HallController@rateHall')->name('halls.rate');
        Route::post('/halls/rate/active/{id}', 'HallController@activeHall')->name('halls.active');
        Route::post('/halls/rate/note', 'HallController@rateNote')->name('rate.note');
        Route::get('/halls/reservations/{id}', 'HallController@reservations')->name('halls.reservations');
        Route::get('/halls/get/pendings', 'HallController@pendingHalls')->name('get.pending.halls');
        Route::get('/halls/list', 'HallController@listHalls')->name('halls.list');
        Route::resource('/roles', 'RoleController');
        Route::resource('/users', 'UserController');
        Route::get('/users/search/all', 'UserController@search')->name('search.user');
        Route::post('/users/status', 'UserController@changeStatus')->name('users.status');
        Route::get('/profile/edit', 'UserController@editProfile')->name('profile.edit');
        Route::put('/profile/update', 'UserController@updateProfile')->name('profile.update');
        Route::get('/user/get/reservations', 'UserController@getReservations')->name('user.reservations');
        Route::resource('/categories', 'CategoryController');
        Route::get('/categories/extra/get', 'CategoryController@getExtra')->name('categories.extra');
        Route::resource('/category_extras', 'CategoryExtraController');
        Route::resource('/cities', 'CityController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/reservations', 'ReservationController');
        Route::post('/reservations/cancel/{id}', 'ReservationController@cancelReservation')->name('reservations.cancel');
        Route::post('/reservations/status/{id}', 'ReservationController@reservationStatus')->name('reservations.status');
        Route::resource('/media', 'HallMediaController');
        Route::resource('/inquiries', 'InquiryController');
        Route::resource('/ads', 'AdsController');
        Route::resource('/prices', 'HallPriceController');
        Route::post('/prices/sort/hall', 'HallPriceController@sortPrices')->name('prices.sort');
        Route::get('/halls/search', 'HallController@search')->name('halls.search');
        Route::get('/calendar', 'CalendarController@index')->name('calendar.index');

        Route::post('calendar/get/events','CalendarController@getEvents')->name('get.events');
        Route::post('calendar/create','CalendarController@create')->name('event.add');
        Route::post('calendar/resize','CalendarController@resize')->name('event.resize');
        Route::post('calendar/update','CalendarController@update')->name('event.update');
        Route::post('calendar/delete','CalendarController@destroy')->name('event.destroy');


        Route::get('/notifications','NotificationController@getNew')->name('notifications.new');


        Route::resource('/alerts','AlertController');
        Route::post('/alert/send','AlertController@send')->name('alerts.send');

        Route::get('/hall/add/favorite/{id}', 'HallController@addFavorite')->name('hall.add.favorite');
        Route::get('/hall/remove/favorite/{id}', 'HallController@removeFavorite')->name('hall.remove.favorite');
        Route::get('/hall/favorite/show', 'HallController@favorite')->name('halls.favorite');
        Route::get('/halls/get/favorite', 'HallController@getFavorite')->name('halls.get.favorite');
        Route::post('/hall/get/reserved', 'HallController@getHallReserved')->name('hall.reserved');
        Route::get('/myHalls', 'HallController@getMyHalls');
    });
    Route::get('/halls/get/maps', 'HallController@hallsOnMap')->name('get.halls.map');

    Route::resource('/halls', 'HallController');
    Route::get('/halls/get/ajax', 'HallController@getHallsAjax')->name('get.halls');
    Route::get('/halls/search/all', 'HallController@search')->name('search.hall');
    Route::resource('/partners', 'PartnerController');
    Route::get('/partners/main/{id}', 'PartnerController@main');
    Route::get('/partners/getSalesMen/{id}', 'PartnerController@getSalesMen');

    Route::get('/partners/branches/{id}', 'PartnerController@branches');
    Route::post('/partners/addBranch', 'PartnerController@addBranch');
    Route::post('/partners/updateBranch', 'PartnerController@updateBranch');
    Route::get('/partners/coupons/{id}', 'PartnerController@coupons');
    // Route::get('/partners/coupons/{id}/details', 'PartnerController@couponDetails');
    Route::get('/partners/branch/{id}/details', 'PartnerController@branchDetails');
    Route::post('/partners/product/edit', 'PartnerController@editProduct');
    Route::post('/partners/product/updatediscountPerProduct', 'PartnerController@updatediscountPerProduct');
    Route::post('/partners/product/add', 'PartnerController@addProd');
    Route::post('/partnersCouponeAdd', 'PartnerController@partnersCouponeAdd');
    Route::post('/partners/product/update/existProduct', 'PartnerController@editExistProduct');
    // Route::get('/partners/discount/edit', 'PartnerController@eDiscountType');
    Route::get('/partners/discount/edit', 'PartnerController@edit');
    Route::get('/partners/product/remove/{id}/{p}', 'PartnerController@removeProduct');
    Route::get('/partners/Branch/addNew/{id}', 'PartnerController@addNew');
    Route::get('/partners/Branch/edit/{id}/{b_id}', 'PartnerController@editBranch');
    Route::get('/partners/product/update/{id}/{p}', 'PartnerController@goToEditProductPage');
    Route::get('/partners/salesman/store/', 'PartnerController@addSalesMan');

});

Route::post('/test', 'admin\HallController@store');
Route::get('/user-guide',function () {
    return view('user-guide');
});
Route::get('/contact-us', 'admin\UserController@contact_us');

app/models/Inquiry.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Inquiry extends Model
{
    protected $guarded = ['id', 'created_at', 'updated_at'];

    public function user () {
        return $this->belongsTo('App\models\User');
    }

    public function admin () {
        return $this->belongsTo('App\models\User', 'admin_id');
    }
}

app/Http/Controllers/admin/InquiryController.php
<?php

namespace App\Http\Controllers\admin;

use App\models\Inquiry;
use Carbon\Carbon;
use App\models\Notification;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class InquiryController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $model_instance;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view = 'admin.inquiries.index';
        $this->create_view = 'admin.inquiries.create';
        $this->show_view = 'admin.inquiries.show';
        $this->edit_view = 'admin.inquiries.edit';
        $this->index_route = 'admin.inquiries.index';
        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_created_successfully');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
        $this->model_instance = Inquiry::class;
    }

    private function UpdateValidationRules()
    {
        return [
            'answer' => 'required|string|min:3|max:200',
        ];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        has_access('show_inquiries');
        Notification::where('type','inquery')->update(["is_new"=>'no','notified'=>'yes']);

        $inquiries = $this->model_instance::orderBy('id', 'desc')->get();
        return view($this->index_view, compact('inquiries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        has_access('update_inquiries');
        $inquiry = $this->model_instance::find($id);
        return view($this->edit_view, compact(['inquiry']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        has_access('update_inquiries');
        $validated_data = $request->validate($this->UpdateValidationRules());
        try {
            DB::beginTransaction();
            $validated_data['admin_id'] = Auth::id();
            $validated_data['answer_date'] = Carbon::now();
            $validated_data['notified'] = 'no';
            $updated_instance = $this->model_instance::find($id);
            $updated_instance->update($validated_data);

            DB::commit();
            return redirect()->route($this->index_route)->with('success', $this->success_message);
        } catch (\Exception $ex) {
            DB::rollBack();
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }
    }

    public function destroy(Request $request, $id)
    {
        has_access('delete_inquiries');
        if ($request->ajax()) {
            $deleted = $this->model_instance::findOrFail($id)->delete();
            if ($deleted) {
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }

        }

        return redirect()->route($this->index_route);
    }
}

app/Http/Controllers/api/admin/InquiryController.php
<?php

namespace App\Http\Controllers\api\admin;

use App\models\Inquiry;
use Carbon\Carbon;
use App\models\Notification;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class InquiryController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $model_instance;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view = 'admin.inquiries.index';
        $this->create_view = 'admin.inquiries.create';
        $this->show_view = 'admin.inquiries.show';
        $this->edit_view = 'admin.inquiries.edit';
        $this->index_route = 'admin.inquiries.index';
        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_created_successfully');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
        $this->model_instance = Inquiry::class;
    }

    private function UpdateValidationRules()
    {
        return [
            'answer' => 'required|string|min:3|max:200',
        ];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        has_access('show_inquiries');
        Notification::where('type','inquery')->update(["is_new"=>'no','notified'=>'yes']);

        $inquiries = $this->model_instance::orderBy('id', 'desc')->get();
        return view($this->index_view, compact('inquiries'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        has_access('update_inquiries');
        $inquiry = $this->model_instance::find($id);
        return view($this->edit_view, compact(['inquiry']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        has_access('update_inquiries');
        $validated_data = $request->validate($this->UpdateValidationRules());
        try {
            DB::beginTransaction();
            $validated_data['admin_id'] = Auth::id();
            $validated_data['answer_date'] = Carbon::now();
            $validated_data['notified'] = 'no';
            $updated_instance = $this->model_instance::find($id);
            $updated_instance->update($validated_data);

            DB::commit();
            return redirect()->route($this->index_route)->with('success', $this->success_message);
        } catch (\Exception $ex) {
            DB::rollBack();
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }
    }

    public function destroy(Request $request, $id)
    {
        has_access('delete_inquiries');
        if ($request->ajax()) {
            $deleted = $this->model_instance::findOrFail($id)->delete();
            if ($deleted) {
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }

        }

        return redirect()->route($this->index_route);
    }
}

resources/views/admin/inquiries/create.blade.php
@extends('layouts.app')

@section('title',trans('categories.create'))

@section('content')

    <h1>Create</h1>

@endsection

resources/views/admin/inquiries/edit.blade.php
@extends('layouts.app')

@section('title',trans('companytypes.edit'))

@section('content')

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">@lang('companytypes.edit')</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.companytypes.update',$type->id) }}">
                            @csrf
                            @method('put')

                            <div class="form-group row">
                                <label class="col-md-4 col-form-label text-md-right">@lang('companytypes.name')</label>

                                <div class="col-md-6">
                                    <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $type->name }}" required autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>



                            <div class="form-group row mb-0">
                                <div class="col-md-8 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        @lang('admin.edit')
                                    </button>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection

resources/views/admin/inquiries/index.blade.php
@extends('layouts.app')

@section('title',trans('sidebar.inquiries'))

@section('content')

    <div class="container-fluid">

        <div class="row">
            <div class="col-lg-12">
                @include('flash-message')
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">@lang('sidebar.inquiries')</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class=" table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <tr>
                            <th>@lang('inquiries.id')</th>
                            <th>@lang('inquiries.user')</th>
                            <th>@lang('inquiries.question')</th>
                            <th>@lang('inquiries.admin')</th>
                            <th>@lang('inquiries.answer')</th>
                            <th>@lang('admin.settings')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($inquiries as $inquiry)
                            <tr class="odd gradeX">
                                <td>{{ $inquiry->id }}</td>
                                <td>{{ $inquiry->user->identity ?? '' }}</td>
                                <td>{{ $inquiry->question ?? '' }}</td>
                                <td>{{ $inquiry->admin->email ?? '' }}</td>
                                <td>{{ $inquiry->answer ?? '' }}</td>
                                <input type="hidden" id="inquiry-question-{{ $inquiry->id }}" value="{{ $inquiry->question ?? '' }}">
                                <input type="hidden" id="inquiry-answer-{{ $inquiry->id }}" value="{{ $inquiry->answer ?? '' }}">
                                <td>
                                    @ifCanDo('update_inquiries')
                                    <a data-toggle="modal" style="cursor: pointer; color: #4e73df" data-target="#EditModal" onclick="updateItem({{ $inquiry->id }},'{{ route('admin.inquiries.update',$inquiry->id) }}')" data-toggle="tooltip" title="@lang('admin.edit')"><i class="fa fa-edit"></i> </a> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
                                    @endif
                                    {{-- @ifCanDo('delete_inquiries')
                                    <a href="#" style="color: #dc3545" data-toggle="tooltip" title="@lang('admin.delete')" onclick="event.preventDefault();deleteItem('{{ $inquiry->id }}','{{ route('admin.inquiries.destroy',$inquiry->id) }}')"><i class="fa fa-trash"></i></a>
                                    @endif --}}
                                </td>
                            </tr>
                        @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
                <br>
                @ifCanDo('create_inquiries')
                <div class="panel-footer">
                    <button  data-toggle="modal" data-target="#myModal" class="btn btn-primary" ><i class="fa fa-plus"></i> @lang('admin.add_new')</button>
                </div>
                @endif
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>

    <!-- The Modal -->
    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="POST" action="{{ route('admin.inquiries.store') }}" enctype="multipart/form-data">
                    @csrf
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">@lang('inquiries.create')</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="text-md-right">@lang('inquiries.name')</label>

                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name" required>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                @enderror

                            </div>
                            <div class="form-group col-md-12">
                                <label class="text-md-right">@lang('inquiries.avatar')</label>

                                <input type="file" class="@error('image') is-invalid @enderror" name="image" style="width: 100%">

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                @enderror

                            </div>
                            <div class="form-group col-md-12">
                                <label class="text-md-right">@lang('inquiries.inquiry_word')</label>

                                <textarea name="inquiry_word" class="form-control @error('inquiry_word') is-invalid @enderror" cols="20" rows="10"></textarea>

                                @error('inquiry_word')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>
                        </div>

                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-success" value="@lang('admin.create')">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">@lang('admin.close')</button>
                    </div>
                </form>


            </div>
        </div>
    </div>

    <!-- The Modal -->
    <div class="modal" id="EditModal">
        <div class="modal-dialog">
            <div class="modal-content">
                <form method="POST" id="edit-form" action="" enctype="multipart/form-data">
                    @csrf
                    @method('PUT')
                    <!-- Modal Header -->
                    <div class="modal-header">
                        <h4 class="modal-title">@lang('inquiries.edit')</h4>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>

                    <!-- Modal body -->
                    <div class="modal-body">
                        <div class="row">
                            <div class="form-group col-md-12">

                                <p id="edit-question"></p>

                            </div>
                            <div class="form-group col-md-12">
                                <label class="text-md-right">@lang('inquiries.answer')</label>

                                <textarea name="answer" id="edit-answer" class="form-control @error('answer') is-invalid @enderror" cols="20" rows="7"></textarea>

                                @error('answer')
                                <span class="invalid-feedback" role="alert">
                                <strong>{{ $message }}</strong>
                            </span>
                                @enderror
                            </div>
                        </div>
                    </div>

                    <!-- Modal footer -->
                    <div class="modal-footer">
                        <input type="submit" class="btn btn-success" value="@lang('admin.edit')">
                        <button type="button" class="btn btn-danger" data-dismiss="modal">@lang('admin.close')</button>
                    </div>
                </form>


            </div>
        </div>
    </div>

@endsection


@section('scripts')
    <script>
        $(document).ready(function() {
            $('#dataTables-example').dataTable({
                "aaSorting": [],
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Arabic.json"
                }
            });

        });



        function deleteItem(id,url) {
            swal({
                title: '{!! trans('admin.are_you_sure') !!}',
                citie: "warning",
                confirmButtonClass: "btn-danger",
                confirmButtonText: "{!! trans('admin.yes'); !!}",
                cancelButtonText: "{!! trans('admin.no'); !!}",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {



                $.ajax({
                    url: url,
                    citie: 'POST',
                    datacitie: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', _method : 'delete' }
                })
                    .done(function() {


                        swal({title: "{!! trans('admin.done') !!}", text: "{!! trans('admin.deleted_successfully') !!}", citie: "success"},
                            function(){
                                location.reload();
                            }
                        );
                    })
                    .fail(function(e) {

                        swal("{!! trans('admin.fail') !!}",e.responseJSON.message, "error")

                    })


            });
        }

        function updateItem(id, url) {
            //alert();
            $('#edit-form').attr("action", url);
            $('#edit-question').html($('#inquiry-question-'+id).val());
            $('#edit-answer').val($('#inquiry-answer-'+id).val());
        }



    </script>

@endsection

resources/views/admin/inquiries/show.blade.php
@extends('layouts.app')

@section('title','')

@section('content')

    <h1>show page</h1>

@endsection