routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', 'Auth\LoginController@loginForm');*/

Auth::routes();
// Route::get('/dd', function () {
//     $img = Image::make(public_path('uploads/ads/s.jpeg')); //1000000

//     return $img->filesize();
// });
Route::get('/', function () {
    return redirect(route('admin.halls.index'));
})->name('home');
Route::get('/home', function () {
    return redirect(route('admin.halls.favorite'));
});

Route::group( [ 'prefix' => 'admin' , 'namespace' => 'admin' , 'as' => 'admin.'], function()
{
    Route::get('/halls/get/pendings/ajax', 'HallController@getPendigHallsAjax')->name('get.pending.halls.ajax');
    Route::group( ['middleware' => ['auth']], function() {
        Route::view('/dashboard', 'admin/dashboard')->name('dashboard');
        Route::post('/halls/rate/hall', 'HallController@rateHall')->name('halls.rate');
        Route::post('/halls/rate/active/{id}', 'HallController@activeHall')->name('halls.active');
        Route::post('/halls/rate/note', 'HallController@rateNote')->name('rate.note');
        Route::get('/halls/reservations/{id}', 'HallController@reservations')->name('halls.reservations');
        Route::get('/halls/get/pendings', 'HallController@pendingHalls')->name('get.pending.halls');
        Route::get('/halls/list', 'HallController@listHalls')->name('halls.list');
        Route::resource('/roles', 'RoleController');
        Route::resource('/users', 'UserController');
        Route::get('/users/search/all', 'UserController@search')->name('search.user');
        Route::post('/users/status', 'UserController@changeStatus')->name('users.status');
        Route::get('/profile/edit', 'UserController@editProfile')->name('profile.edit');
        Route::put('/profile/update', 'UserController@updateProfile')->name('profile.update');
        Route::get('/user/get/reservations', 'UserController@getReservations')->name('user.reservations');
        Route::resource('/categories', 'CategoryController');
        Route::get('/categories/extra/get', 'CategoryController@getExtra')->name('categories.extra');
        Route::resource('/category_extras', 'CategoryExtraController');
        Route::resource('/cities', 'CityController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/reservations', 'ReservationController');
        Route::post('/reservations/cancel/{id}', 'ReservationController@cancelReservation')->name('reservations.cancel');
        Route::post('/reservations/status/{id}', 'ReservationController@reservationStatus')->name('reservations.status');
        Route::resource('/media', 'HallMediaController');
        Route::resource('/inquiries', 'InquiryController');
        Route::resource('/ads', 'AdsController');
        Route::resource('/prices', 'HallPriceController');
        Route::post('/prices/sort/hall', 'HallPriceController@sortPrices')->name('prices.sort');
        Route::get('/halls/search', 'HallController@search')->name('halls.search');
        Route::get('/calendar', 'CalendarController@index')->name('calendar.index');

        Route::post('calendar/get/events','CalendarController@getEvents')->name('get.events');
        Route::post('calendar/create','CalendarController@create')->name('event.add');
        Route::post('calendar/resize','CalendarController@resize')->name('event.resize');
        Route::post('calendar/update','CalendarController@update')->name('event.update');
        Route::post('calendar/delete','CalendarController@destroy')->name('event.destroy');


        Route::get('/notifications','NotificationController@getNew')->name('notifications.new');


        Route::resource('/alerts','AlertController');
        Route::post('/alert/send','AlertController@send')->name('alerts.send');

        Route::get('/hall/add/favorite/{id}', 'HallController@addFavorite')->name('hall.add.favorite');
        Route::get('/hall/remove/favorite/{id}', 'HallController@removeFavorite')->name('hall.remove.favorite');
        Route::get('/hall/favorite/show', 'HallController@favorite')->name('halls.favorite');
        Route::get('/halls/get/favorite', 'HallController@getFavorite')->name('halls.get.favorite');
        Route::post('/hall/get/reserved', 'HallController@getHallReserved')->name('hall.reserved');
        Route::get('/myHalls', 'HallController@getMyHalls');
    });
    Route::get('/halls/get/maps', 'HallController@hallsOnMap')->name('get.halls.map');

    Route::resource('/halls', 'HallController');
    Route::get('/halls/get/ajax', 'HallController@getHallsAjax')->name('get.halls');
    Route::get('/halls/search/all', 'HallController@search')->name('search.hall');
    Route::resource('/partners', 'PartnerController');
    Route::get('/partners/main/{id}', 'PartnerController@main');
    Route::get('/partners/getSalesMen/{id}', 'PartnerController@getSalesMen');

    Route::get('/partners/branches/{id}', 'PartnerController@branches');
    Route::post('/partners/addBranch', 'PartnerController@addBranch');
    Route::post('/partners/updateBranch', 'PartnerController@updateBranch');
    Route::get('/partners/coupons/{id}', 'PartnerController@coupons');
    // Route::get('/partners/coupons/{id}/details', 'PartnerController@couponDetails');
    Route::get('/partners/branch/{id}/details', 'PartnerController@branchDetails');
    Route::post('/partners/product/edit', 'PartnerController@editProduct');
    Route::post('/partners/product/updatediscountPerProduct', 'PartnerController@updatediscountPerProduct');
    Route::post('/partners/product/add', 'PartnerController@addProd');
    Route::post('/partnersCouponeAdd', 'PartnerController@partnersCouponeAdd');
    Route::post('/partners/product/update/existProduct', 'PartnerController@editExistProduct');
    // Route::get('/partners/discount/edit', 'PartnerController@eDiscountType');
    Route::get('/partners/discount/edit', 'PartnerController@edit');
    Route::get('/partners/product/remove/{id}/{p}', 'PartnerController@removeProduct');
    Route::get('/partners/Branch/addNew/{id}', 'PartnerController@addNew');
    Route::get('/partners/Branch/edit/{id}/{b_id}', 'PartnerController@editBranch');
    Route::get('/partners/product/update/{id}/{p}', 'PartnerController@goToEditProductPage');
    Route::get('/partners/salesman/store/', 'PartnerController@addSalesMan');

});

Route::post('/test', 'admin\HallController@store');
Route::get('/user-guide',function () {
    return view('user-guide');
});
Route::get('/contact-us', 'admin\UserController@contact_us');

app/models/Alert.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Alert extends Model
{
    protected $guarded = ['id','created_at','updated_at'];
}

app/Http/Controllers/admin/AlertController.php
<?php

namespace App\Http\Controllers\admin;

use App\models\Alert;
use App\models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class AlertController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $model_instance;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view = 'admin.alerts.index';
        $this->create_view = 'admin.alerts.create';
        $this->show_view = 'admin.alerts.show';
        $this->edit_view = 'admin.alerts.edit';
        $this->index_route = 'admin.alerts.index';
        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_created_successfully');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
        $this->model_instance = Alert::class;
    }

    private function StoreValidationRules()
    {
        return [
            'title' => 'required|string|min:3|max:200',
            'message' => 'required|string|min:3|max:200',
        ];
    }

    private function UpdateValidationRules()
    {
        return [
            'title' => 'sometimes|string|min:3|max:200',
            'message' => 'sometimes|string|min:3|max:200',
        ];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {

        $app_alerts = $this->model_instance::all();
        return view($this->index_view, compact('app_alerts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {


        return view($this->create_view);
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $validated_data = $request->validate($this->StoreValidationRules());

        try {

            $object = $this->model_instance::create($validated_data);

            return redirect()->route($this->index_route)->with('success', $this->success_message);
        } catch (\Exception $ex) {
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $alerts = $this->model_instance::findOrFail($id);

        return view($this->edit_view, compact(['alerts']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

        $validated_data = $request->validate($this->UpdateValidationRules());

        try {
            $object = $this->model_instance::find($id);
            $updated_instance = $object->update($validated_data);


            if ($updated_instance) {
                return redirect()->route($this->index_route)->with('success', $this->update_success_message);
            } else {
                return redirect()->route($this->index_route)->with('error', $this->update_error_message);
            }



        } catch (\Exception $ex) {
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, $id)
    {

        if ($request->ajax()) {
            $deleted = $this->model_instance::findOrFail($id)->delete();
            if ($deleted) {
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }

        }

        return redirect()->route($this->index_route);
    }


    public function send(Request $request)
    {

        has_access('alert_send');

        $alert = Alert::findOrFail($request->alert_id);
        $send_result = $this->sendNotifications($alert->title,$alert->message);
        if($send_result)
        {

            return response()->json(['status' => 'success']);
        }


        return response()->json(['status' => 'fail']);


    }

    private function sendNotifications($title,$message)
    {

        $notification = [
            'title' => $title,
            'body' => $message,
            'priority' => 'high'
        ];
 
        User::sendPublicNotifications($notification);

        return true;
    }
}

app/Http/Controllers/api/admin/AlertController.php
<?php

namespace App\Http\Controllers\api\admin;

use Illuminate\Support\Facades\Validator;

use App\models\Alert;
use App\models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;

class AlertController extends Controller
{


    private function StoreValidationRules()
    {
        return [
            'title' => 'required|string|min:3|max:200',
            'message' => 'required|string|min:3|max:200',
        ];
    }

    private function UpdateValidationRules()
    {
        return [
            'title' => 'sometimes|string|min:3|max:200',
            'message' => 'sometimes|string|min:3|max:200',
        ];
    }

    public function index()
    {

        $app_alerts = Alert::all();
        return response()->api($app_alerts, null);
    }

    public function store(Request $request)
    {

        $validator = Validator::make($request->all(), $this->StoreValidationRules());
        if ($validator->fails()) {
            Log::error($validator->errors());
            $data = formatValidationMessages($validator->errors()->getMessages());
            return response()->api($data, "DATA001");
        }

        try {
            $validated_data = $request->validate($this->StoreValidationRules());

            $object = Alert::create($validated_data);

            return response()->api(null, null);
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return response()->api($ex->getMessage(), "DATA001");
        }

    }

    public function update(Request $request, $id)
    {

        $validator = Validator::make($request->all(), $this->UpdateValidationRules());
        if ($validator->fails()) {
            Log::error($validator->errors());
            $data = formatValidationMessages($validator->errors()->getMessages());
            return response()->api($data, "DATA001");
        }
        try {
            $validated_data = $request->validate($this->UpdateValidationRules());

            $object = Alert::find($id);
            $updated_instance = $object->update($validated_data);


            if ($updated_instance) {
                return response()->api(null, null);
            } else {
                return response()->api(null, "_GENERAL000");
            }



        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return response()->api($ex->getMessage(), "DATA001");
        }


    }


    public function destroy(Request $request, $id)
    {
        try {
            $deleted = Alert::findOrFail($id)->delete();
            if ($deleted) {
            return response()->api(null, null);
            } else {
            return response()->api(null, "_GENERAL000");
            }
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return response()->api(null, "_GENERAL000");
        }
    }


    public function send(Request $request)
    {
        $alert = Alert::findOrFail($request->alert_id);
        $send_result = $this->sendNotifications($alert->title,$alert->message);
        if($send_result)
        {
            return response()->api(null, null);
        }
        return response()->api(null, "_GENERAL000");
    }

    private function sendNotifications($title,$message)
    {
        $notification = [
            'title' => $title,
            'body' => $message,
            'priority' => 'high'
        ];
        User::sendPublicNotifications($notification);
        return response()->api(null, null);
    }
}

resources/views/admin/alerts/create.blade.php
@extends('layouts.app')

@section('title',trans('ads.create'))


@section('styles')

    <style>
        .wrapper-pic {
            position: relative;
            display: inline-block;
            opacity: 1;
        }

        .wrapper-pic:hover {
            transition: all .2s ease-in-out;
        }

        .wrapper-pic:hover .edit {
            transition: all .2s ease-in-out;
            display: block;
        }

        .edit {
            padding-top: 7px;
            padding-right: 7px;
            position: absolute;
            left: 20px;
            top: 10px;
            display: none;
        }
    </style>

@endsection

@section('content')


    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-12">
                @include('flash-message')
            </div>
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-header">@lang('ads.create')</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('admin.ads.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="row">
                                <div class="col-md-8">


                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.title')</label>

                                <div class="col-md-10">
                                    <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" required autofocus>

                                    @error('title')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.type')</label>

                                <div class="col-md-10">
                                    <select name="type" class="form-control" onchange="get_item_data(event)">
                                        <option value="product" selected>@lang('ads.product')</option>
                                        <option value="category">@lang('ads.category')</option>
                                        <option value="ads">@lang('ads.ads')</option>
                                        <option value="offers">@lang('ads.offers')</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.item')</label>

                                <div class="col-md-10">
                                    <select class="form-control" id="ads_item">

                                    </select>
                                </div>
                            </div>

                            <div class="form-group row">
                                <label class="col-md-2 col-form-label text-md-right">@lang('ads.image')</label>

                                <div class="col-md-10">
                                    <input type="file" name="image" class="form-control">
                                </div>
                            </div>

                                    <input type="hidden" id="selected_item" name="item_id">


                            <div class="form-group row mb-0">
                                <div class="col-md-12 offset-md-2">
                                    <button type="submit" class="btn btn-primary">
                                       @lang('admin.create')
                                    </button>

                                </div>
                            </div>

                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection


@section('scripts')
    <script>
        function enableCategorySearching() {
            var searchUrl = '{{ route('admin.categories.search') }}';
            searchingFor(searchUrl);
            attachCategory();


        }

        function attachCategory(){
            $('#ads_item').off('select2:select').on('select2:select', function (event) {
                var id = $(event.currentTarget).find("option:selected").val();
                if(confirm('@lang('admin.sure_to_add_category')'))
                {
                    $('#selected_item').attr('value',id);
                }
            });
        }

        function attachProduct(){
            $('#ads_item').off('select2:select').on('select2:select', function (event) {
                var id = $(event.currentTarget).find("option:selected").val();
                if(confirm('@lang('admin.sure_to_add_product')'))
                {
                    $('#selected_item').attr('value',id);
                }
            });
        }

        function enableProductSearching() {
            var searchUrl = '{{ route('admin.products.search') }}';
            searchingFor(searchUrl);
            attachProduct();
        }


        function searchingFor(url)
        {
            //console.log(url);
            if(url === '')
            {
                return;
            }
            $('#ads_item').empty();
            $('#ads_item').select2({
                placeholder: "@lang('admin.type_search_word')",
                minimumInputLength: 2,
                ajax: {
                    url: url,
                    dataType: 'json',
                    data: function (params) {
                        return {
                            q: $.trim(params.term)
                        };
                    },
                    processResults: function (data) {
                      //  console.log(data);
                        return {
                            results: data
                        };
                    },
                    error: function (err) {
                        console.log(err);
                    },
                    cache: true
                }
            });
        }






       function get_item_data(event)
        {
            var selected_value  = $(event.target).val();
            if(selected_value === "product")
                enableProductSearching();
            else if(selected_value === "category")
                enableCategorySearching();
            else if(selected_value === "ads")
            {
                $('#ads_item').empty();
                var ele = `<option value="ads">اعلان مجرد</option>`;
                $('#ads_item').append(ele);
            }
            else if(selected_value === "offers")
            {
                $('#ads_item').empty();
                var ele = `<option value="offers">اعلان لصفحة العروض</option>`;
                $('#ads_item').append(ele);
            }
        }

        enableProductSearching();


    </script>
@endsection

resources/views/admin/alerts/index.blade.php
@extends('layouts.app')

@section('title',trans('alerts.alerts'))

@section('content')

    <div class="container-fluid">

        <div class="row">
            <div class="col-lg-12">
                @include('flash-message')
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">@lang('alerts.alerts')</h1>
                <hr>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="table-responsive">
                    <table class=" table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                        <tr>
                            <th>@lang('alerts.id')</th>
                            <th>@lang('alerts.title')</th>
                            <th>@lang('alerts.message')</th>
                            <th>@lang('admin.settings')</th>
                        </tr>
                        </thead>
                        <tbody>
                        @foreach($app_alerts as $alert)
                            <tr class="odd gradeX">
                                <td>{{ $alert->id }}</td>
                                <td>{{ $alert->title ?? '' }}</td>
                                <td>{{ $alert->message ?? '' }}</td>
                                <td>
                                    <a href="#" style="color: #dc3545" onclick="event.preventDefault();deleteItem('{{ $alert->id }}','{{ route('admin.alerts.destroy',$alert->id) }}')"><i class="fa fa-trash"></i></a>&nbsp;
                                    <a href="#" style="color: #0e0e0e" onclick="event.preventDefault();sendAlert('{{ $alert->id }}','{{ route('admin.alerts.send') }}')"><i class="fas fa-paper-plane"></i></a>&nbsp;
                                </td>
                            </tr> 
                        @endforeach


                        </tbody>
                    </table>
                </div>
                <!-- /.table-responsive -->
                <br>
                <div class="panel-footer">
                    <a href="#" data-toggle="modal" data-target="#add_alert_modal" class="btn btn-primary" ><i class="fa fa-plus"></i> @lang('admin.add_new')</a>
                </div>
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>


    <div class="modal" id="add_alert_modal">
        <div class="modal-dialog">
            <div class="modal-content">

                <!-- Modal Header -->
                <div class="modal-header">
                    <h4 class="modal-title">@lang('alerts.create')</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <div class="row">
                        <div class="col">
                            <form action="{{ route('admin.alerts.store') }}" method="POST" id="add_alert_form">
                                @csrf
                                <div class="form-group row">
                                    <label class="col-md-4 col-form-label text-md-right">@lang('alerts.title')</label>

                                    <div class="col-md-8">
                                        <input type="text" class="form-control @error('title') is-invalid @enderror" name="title" required autofocus>

                                        @error('title')
                                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                        @enderror
                                    </div>
                                </div>

                                <div class="form-group row">
                                    <label class="col-md-4 col-form-label text-md-right">@lang('alerts.message')</label>

                                    <div class="col-md-8">
                                        <textarea name="message" class="form-control" cols="30" rows="10"></textarea>
                                    </div>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>

                <!-- Modal footer -->
                <div class="modal-footer">

                    <button type="button" onclick="$('#add_alert_form').submit()" class="btn btn-primary">@lang('admin.save')</button>
                    <button type="button" class="btn btn-danger" data-dismiss="modal">@lang('admin.close')</button>
                </div>

            </div>
        </div>
    </div>



@endsection


@section('scripts')
    <script>
        $(document).ready(function() {
            $('#dataTables-example').dataTable({
                "language": {
                    "url": "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Arabic.json"
                }
            });

        });



        function deleteItem(id,url) {
            swal({
                title: '{!! trans('admin.are_you_sure') !!}',
                type: "warning",
                confirmButtonClass: "btn-danger",
                confirmButtonText: "{!! trans('admin.yes'); !!}",
                cancelButtonText: "{!! trans('admin.no'); !!}",
                showCancelButton: true,
                closeOnConfirm: false,
                showLoaderOnConfirm: true
            }, function () {



                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', _method : 'delete' }
                })
                    .done(function() {


                        swal({title: "{!! trans('admin.done') !!}", text: "{!! trans('admin.deleted_successfully') !!}", type: "success"},
                            function(){
                                location.reload();
                            }
                        );


                    })
                    .fail(function(e) {

                        swal("{!! trans('admin.fail') !!}",e.responseJSON.message, "error")

                    })


            });
        }



        function sendAlert(id,url) {

                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', alert_id : id }
                })
                    .done(function() {


                        swal({title: "{!! trans('admin.done') !!}", text: "{!! trans('admin.sent_successfully') !!}", type: "success"},
                            function(){
                                location.reload();
                            }
                        );


                    })
                    .fail(function(e) {

                        console.log(e)



                    })
        }



    </script>

@endsection