routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*Route::get('/', 'Auth\LoginController@loginForm');*/

Auth::routes();
// Route::get('/dd', function () {
//     $img = Image::make(public_path('uploads/ads/s.jpeg')); //1000000

//     return $img->filesize();
// });
Route::get('/', function () {
    return redirect(route('admin.halls.index'));
})->name('home');
Route::get('/home', function () {
    return redirect(route('admin.halls.favorite'));
});

Route::group( [ 'prefix' => 'admin' , 'namespace' => 'admin' , 'as' => 'admin.'], function()
{
    Route::get('/halls/get/pendings/ajax', 'HallController@getPendigHallsAjax')->name('get.pending.halls.ajax');
    Route::group( ['middleware' => ['auth']], function() {
        Route::view('/dashboard', 'admin/dashboard')->name('dashboard');
        Route::post('/halls/rate/hall', 'HallController@rateHall')->name('halls.rate');
        Route::post('/halls/rate/active/{id}', 'HallController@activeHall')->name('halls.active');
        Route::post('/halls/rate/note', 'HallController@rateNote')->name('rate.note');
        Route::get('/halls/reservations/{id}', 'HallController@reservations')->name('halls.reservations');
        Route::get('/halls/get/pendings', 'HallController@pendingHalls')->name('get.pending.halls');
        Route::get('/halls/list', 'HallController@listHalls')->name('halls.list');
        Route::resource('/roles', 'RoleController');
        Route::resource('/users', 'UserController');
        Route::get('/users/search/all', 'UserController@search')->name('search.user');
        Route::post('/users/status', 'UserController@changeStatus')->name('users.status');
        Route::get('/profile/edit', 'UserController@editProfile')->name('profile.edit');
        Route::put('/profile/update', 'UserController@updateProfile')->name('profile.update');
        Route::get('/user/get/reservations', 'UserController@getReservations')->name('user.reservations');
        Route::resource('/categories', 'CategoryController');
        Route::get('/categories/extra/get', 'CategoryController@getExtra')->name('categories.extra');
        Route::resource('/category_extras', 'CategoryExtraController');
        Route::resource('/cities', 'CityController');
        Route::resource('/coupons', 'CouponController');
        Route::resource('/reservations', 'ReservationController');
        Route::post('/reservations/cancel/{id}', 'ReservationController@cancelReservation')->name('reservations.cancel');
        Route::post('/reservations/status/{id}', 'ReservationController@reservationStatus')->name('reservations.status');
        Route::resource('/media', 'HallMediaController');
        Route::resource('/inquiries', 'InquiryController');
        Route::resource('/ads', 'AdsController');
        Route::resource('/prices', 'HallPriceController');
        Route::post('/prices/sort/hall', 'HallPriceController@sortPrices')->name('prices.sort');
        Route::get('/halls/search', 'HallController@search')->name('halls.search');
        Route::get('/calendar', 'CalendarController@index')->name('calendar.index');

        Route::post('calendar/get/events','CalendarController@getEvents')->name('get.events');
        Route::post('calendar/create','CalendarController@create')->name('event.add');
        Route::post('calendar/resize','CalendarController@resize')->name('event.resize');
        Route::post('calendar/update','CalendarController@update')->name('event.update');
        Route::post('calendar/delete','CalendarController@destroy')->name('event.destroy');


        Route::get('/notifications','NotificationController@getNew')->name('notifications.new');


        Route::resource('/alerts','AlertController');
        Route::post('/alert/send','AlertController@send')->name('alerts.send');

        Route::get('/hall/add/favorite/{id}', 'HallController@addFavorite')->name('hall.add.favorite');
        Route::get('/hall/remove/favorite/{id}', 'HallController@removeFavorite')->name('hall.remove.favorite');
        Route::get('/hall/favorite/show', 'HallController@favorite')->name('halls.favorite');
        Route::get('/halls/get/favorite', 'HallController@getFavorite')->name('halls.get.favorite');
        Route::post('/hall/get/reserved', 'HallController@getHallReserved')->name('hall.reserved');
        Route::get('/myHalls', 'HallController@getMyHalls');
    });
    Route::get('/halls/get/maps', 'HallController@hallsOnMap')->name('get.halls.map');

    Route::resource('/halls', 'HallController');
    Route::get('/halls/get/ajax', 'HallController@getHallsAjax')->name('get.halls');
    Route::get('/halls/search/all', 'HallController@search')->name('search.hall');
    Route::resource('/partners', 'PartnerController');
    Route::get('/partners/main/{id}', 'PartnerController@main');
    Route::get('/partners/getSalesMen/{id}', 'PartnerController@getSalesMen');

    Route::get('/partners/branches/{id}', 'PartnerController@branches');
    Route::post('/partners/addBranch', 'PartnerController@addBranch');
    Route::post('/partners/updateBranch', 'PartnerController@updateBranch');
    Route::get('/partners/coupons/{id}', 'PartnerController@coupons');
    // Route::get('/partners/coupons/{id}/details', 'PartnerController@couponDetails');
    Route::get('/partners/branch/{id}/details', 'PartnerController@branchDetails');
    Route::post('/partners/product/edit', 'PartnerController@editProduct');
    Route::post('/partners/product/updatediscountPerProduct', 'PartnerController@updatediscountPerProduct');
    Route::post('/partners/product/add', 'PartnerController@addProd');
    Route::post('/partnersCouponeAdd', 'PartnerController@partnersCouponeAdd');
    Route::post('/partners/product/update/existProduct', 'PartnerController@editExistProduct');
    // Route::get('/partners/discount/edit', 'PartnerController@eDiscountType');
    Route::get('/partners/discount/edit', 'PartnerController@edit');
    Route::get('/partners/product/remove/{id}/{p}', 'PartnerController@removeProduct');
    Route::get('/partners/Branch/addNew/{id}', 'PartnerController@addNew');
    Route::get('/partners/Branch/edit/{id}/{b_id}', 'PartnerController@editBranch');
    Route::get('/partners/product/update/{id}/{p}', 'PartnerController@goToEditProductPage');
    Route::get('/partners/salesman/store/', 'PartnerController@addSalesMan');

});

Route::post('/test', 'admin\HallController@store');
Route::get('/user-guide',function () {
    return view('user-guide');
});
Route::get('/contact-us', 'admin\UserController@contact_us');

app/models/Category.php
<?php

namespace App\models;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    protected $guarded = ['id','created_at','updated_at'];

    public function extras() {
        return $this->hasMany('App\models\CategoryExtra');
    }



public function updateRelations()
{
    //dd(request()->extras);
    if (request()->has('extras') && !empty(request()->extras)) {
        //dd(request()->extras);
        foreach (request()->extras as $extra) {
            if (empty($extra['id'])) {
                $insert = [
                    'category_id' => $this->id,
                    'field_name' => $extra['title'],
                    'field_type' => $extra['type'],
                    'field_values' => isset($extrvaluesa['']) ? implode(',', $extra['values']) : null,
                ];
                CategoryExtra::create($insert);
            } else {
                $category_extra = CategoryExtra::find($extra['id']);
                $update = [
                    'category_id' => $this->id,
                    'field_name' => $extra['title'],
                    'field_type' => $extra['type'],
                    'field_values' => isset($extra['values']) ? implode(',', $extra['values']) : null,
                ];
                $category_extra->update($update);
            }

        }
    }
}

    public static function boot()
    {
        parent::boot();
        static::created(function($category)
        {
            //dd(request()->extras);
            if (request()->has('extras') && !empty(request()->extras)) {
                foreach (request()->extras as $extra) {
                    $insert = [
                        'category_id' => $category->id,
                        'field_name' => $extra['title'],
                        'field_type' => $extra['type'],
                        'field_values' => isset($extra['values']) ? implode(',', $extra['values']) : null,
                    ];
                    CategoryExtra::create($insert);
                }
            }
        });


        static::deleting(function($category)
        {
            CategoryExtra::where('category_id', $category->id)->delete();
        });
    }
}

app/Http/Controllers/admin/CategoryController.php
<?php

namespace App\Http\Controllers\admin;

use App\models\Category;
use App\models\CategoryExtra;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class CategoryController extends Controller
{
    private $index_view;
    private $create_view;
    private $edit_view;
    private $show_view;
    private $index_route;
    private $model_instance;
    private $success_message;
    private $error_message;
    private $update_success_message;
    private $update_error_message;

    public function __construct()
    {
        $this->index_view = 'admin.categories.index';
        $this->create_view = 'admin.categories.create';
        $this->show_view = 'admin.categories.show';
        $this->edit_view = 'admin.categories.edit';
        $this->index_route = 'admin.categories.index';
        $this->success_message = trans('admin.created_successfully');
        $this->update_success_message = trans('admin.update_created_successfully');
        $this->error_message = trans('admin.fail_while_create');
        $this->update_error_message = trans('admin.fail_while_update');
        $this->model_instance = Category::class;
    }

    private function StoreValidationRules()
    {
        return [
            'name' => 'required|string|min:3|max:200',
        ];
    }

    private function UpdateValidationRules()
    {
        return [
            'name' => 'required|string|min:3|max:200',
        ];
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        has_access('show_categories');
        $categories = $this->model_instance::all();
        return view($this->index_view, compact('categories'));
    }

    public function getExtra (Request $request) {
        has_access('show_categories');
        if ($request->ajax()){
            $extra = CategoryExtra::where('category_id', $request->id)->get();
            return response()->json($extra);
        }
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        has_access('create_categories');
        return view($this->create_view);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        has_access('create_categories');
        $validated_data = $request->validate($this->StoreValidationRules());


        try {
            DB::beginTransaction();
            $this->model_instance::create($validated_data);

            DB::commit();
            return redirect()->route($this->index_route)->with('success', $this->success_message);
        } catch (\Exception $ex) {
            DB::rollBack();
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }


    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        has_access('update_categories');
        $category = $this->model_instance::find($id);
        $i = 1;
        //dd($category->extras->toArray());
        return view($this->edit_view, compact(['category', 'i']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        has_access('update_categories');
        $validated_data = $request->validate($this->UpdateValidationRules());
        try {
            DB::beginTransaction();
            $updated_instance = $this->model_instance::find($id);
            $updated_instance->update($validated_data);
            $updated_instance->updateRelations();

            DB::commit();
            return redirect()->route($this->index_route)->with('success', $this->success_message);
        } catch (\Exception $ex) {
            DB::rollBack();
            dd($ex->getMessage());
            Log::error($ex->getMessage());
            return redirect()->route($this->index_route)->with('error', $this->error_message);
        }
    }

    public function destroy(Request $request, $id)
    {
        has_access('delete_categories');
        if ($request->ajax()) {
            $deleted = $this->model_instance::findOrFail($id)->delete();
            if ($deleted) {
                return response()->json(['status' => 'success', 'message' => 'deleted_successfully']);
            } else {
                return response()->json(['status' => 'fail', 'message' => 'fail_while_delete']);
            }

        }

        return redirect()->route($this->index_route);
    }
}

app/Http/Controllers/api/CategoryController.php
<?php

namespace App\Http\Controllers\api;

use App\Http\Resources\CategoryCollection;
use App\models\Category;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class CategoryController extends Controller
{
    public function index()
    {
        $categories = Category::all();

        return new CategoryCollection($categories);
    }
}

app/Http/Controllers/api/admin/CategoryController.php
<?php

namespace App\Http\Controllers\api\admin;

use App\Http\Resources\CategoryCollection;
use App\models\Category;
use App\models\CategoryExtra;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Validator;

class CategoryController extends Controller
{
    private function StoreValidationRules()
    {
        return [
            'name' => 'required|string|min:3|max:200',
        ];
    }

    private function UpdateValidationRules()
    {
        return [
            'name' => 'required|string|min:3|max:200',
        ];
    }

    public function index()
    {
        $categories = Category::all();
        return response()->api(new CategoryCollection($categories), null);
    }

    public function getExtra($id) {
       
            $extra = CategoryExtra::where('category_id', $id)->get();
            return response()->api($extra, null);

    }

    public function store(Request $request)
    {
        $validator = Validator::make($request->all(), $this->StoreValidationRules($request));
        if ($validator->fails()) {
            Log::error($validator->errors());
            $data = formatValidationMessages($validator->errors()->getMessages());
            return response()->api($data, "DATA001");
        }
        try {
            DB::beginTransaction();
            $validated_data = $request->validate($this->StoreValidationRules($request));

            Category::create($validated_data);

            DB::commit();
            return response()->api(null, null);
        } catch (\Exception $ex) {
            DB::rollBack();
            Log::error($ex->getMessage());
            return response()->api($ex->getMessage(), "DATA001");
        }
    }
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->UpdateValidationRules($request));
        if ($validator->fails()) {
            Log::error($validator->errors());
            $data = formatValidationMessages($validator->errors()->getMessages());
            return response()->api($data, "DATA001");
        }
        try {
            DB::beginTransaction();
            $validated_data = $request->validate($this->UpdateValidationRules($request));
            $updated_instance = Category::find($id);
            if(!$updated_instance)
                return response()->api(null, "_GENERAL000");

            $updated_instance->update($validated_data);
            $updated_instance->updateRelations();
            DB::commit();
            return response()->api(null, null);
        } catch (\Exception $ex) {
            DB::rollBack();
            Log::error($ex->getMessage());
            return response()->api($ex->getMessage(), "DATA001");
        }
    }

    public function destroy(Request $request, $id)
    {
        try {

            $deleted = Category::findOrFail($id)->delete();
            if ($deleted) {
                return response()->api(null, null);
            } else {
                return response()->api(null, "_GENERAL000");
            }
        } catch (\Exception $ex) {
            Log::error($ex->getMessage());
            return response()->api(null, "_GENERAL000");
        }

    }

}

resources/views/admin/categories/create.blade.php
<?php //dd($errors) ?>
@extends('layouts.app')

@section('title',trans('categories.create'))

@section('content')

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">@lang('categories.create')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.categories.store') }}" id="main-form">
                        @csrf

                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="text-md-right">@lang('categories.name')</label>

                                <input type="text" class="form-control @error('name') is-invalid @enderror" name="name"
                                       required>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                @enderror

                            </div>
                        </div>
                        <span id="extra"></span>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <input type="button" class="btn btn-success" value="@lang('categories.add_extra')"
                                       onclick="addExtraData()">


                            </div>
                        </div>
                        <hr>
                        <input type="hidden" name="max_extra" id="max_extra">
                        <div class="form-group row mb-0">
                            <div class="col-md-12">
                                <input type="submit" class="btn btn-primary" value="@lang('admin.create')">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('styles')
<style type="text/css">
    .select2-selection__rendered {
        line-height: 31px !important;
    }

    .select2-container .select2-selection--single {
        height: 35px !important;
    }

    .select2-selection__arrow {
        height: 34px !important;
    }
</style>
@endsection
@section('scripts')
<script type="text/javascript">
    $(".select2-single").select2({
        'height': '30px'
    });
    var i = 0;

    function addExtraData() {
        i++;
        var html = `
        <div class="row" id="row${i}">

        <div class="form-group col-md-4">
        <label class="text-md-right">@lang("categories.title")</label>
        <input type="text" class="form-control" name="extras[${i}][title]" required>
        </div>

        <div class="form-group col-md-3">
        <label class="text-md-right">@lang("categories.type")</label>
        <select class="form-control" name="extras[${i}][type]" id="type${i}" onchange="showValues(${i})" required>
        <option value="text">@lang("categories.text")</option>
        <option value="number">@lang("categories.number")</option>
        <option value="select">@lang("categories.select")</option>

        </select>
        </div>

        <div class="form-group col-md-4" style="display: none" id="values-div${i}">
        <label class="text-md-right">@lang("categories.values")</label>
        <select class="form-control selected_values" name="extras[${i}][values][]" multiple></select>
        </div>

        <div class="form-group col-md-1" id="values-div${i}">
        <label class="text-md-right" style="color: #fff">delete</label>
            <input type="button" class="btn btn-danger" onclick="removeRow(${i})" value="@lang('admin.delete')">
        </div>

        </div>`;
        $('#extra').before(html);
        $('#max_extra').val(i);
        $('[data-toggle="tooltip"]').tooltip();
        $(".selected_values").select2({
            tags: true,
            width: '100%'
        });
    }

    function removeRow(i) {
        $('#row'+i).fadeOut(500).remove();
    }

    function showValues(s) {
        if ($('#type' + s).val() == 'select')
            $('#values-div' + s).fadeIn(500).show();
        else
            $('#values-div' + s).fadeOut(500).hide();
    }
</script>
@endsection

resources/views/admin/categories/edit.blade.php
<?php //dd($errors) ?>
@extends('layouts.app')

@section('title',trans('categories.edit'))

@section('content')

<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card">
                <div class="card-header">@lang('categories.edit')</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('admin.categories.update', $category->id) }}" id="main-form">
                        @csrf
                        @method('PUT')
                        <div class="row">
                            <div class="form-group col-md-12">
                                <label class="text-md-right">@lang('categories.name')</label>

                                <input type="text" class="form-control @error('name') is-invalid @enderror" value="{{ $category->name }}" name="name"
                                       required>

                                @error('name')
                                <span class="invalid-feedback" role="alert">
                                                            <strong>{{ $message }}</strong>
                                                        </span>
                                @enderror

                            </div>
                        </div>
                        @forelse($category->extras as $extra)
                        <div class="row" id="row{{ $i }}">
                            <input type="hidden" name="extras[{{ $i }}][id]" value="{{ $extra->id }}">
                            <div class="form-group col-md-4">
                                <label class="text-md-right">@lang("categories.title")</label>
                                <input type="text" class="form-control" name="extras[{{ $i }}][title]" value="{{ $extra->field_name }}" required>
                            </div>

                            <div class="form-group col-md-3">
                                <label class="text-md-right">@lang("categories.type")</label>
                                <select class="form-control" name="extras[{{ $i }}][type]" id="type{{ $i }}" onchange="showValues({{ $i }})" required>
                                    <option value="text" @if($extra->field_type == 'text') selected @endif>@lang("categories.text")</option>
                                    <option value="number" @if($extra->field_type == 'number') selected @endif>@lang("categories.number")</option>
                                    <option value="select" @if($extra->field_type == 'select') selected @endif>@lang("categories.select")</option>
                                </select>
                            </div>

                            <div class="form-group col-md-4" @if($extra->field_type != 'select') style="display: none" @endif id="values-div{{ $i }}">
                                <label class="text-md-right">@lang("categories.values")</label>
                                <select class="form-control selected_values" value="{{ $extra->field_values }}" name="extras[{{ $i }}][values][]" multiple>
                                    @if($extra->field_values)
                                        @forelse(explode(',', $extra->field_values) as $value)
                                            <option value="{{ $value }}" selected>{{ $value }}</option>
                                        @empty
                                        @endforelse
                                    @endif
                                </select>
                            </div>

                            <!-- <div class="form-group col-md-1" id="values-div{{ $i }}">
                                <label class="text-md-right" style="color: #fff">delete</label>
                                <input type="button" class="btn btn-danger" onclick="removeRow({{ $i++ }},'{{ route('admin.category_extras.destroy',$extra->id) }}');" value="@lang('admin.delete')">
                            </div> -->

                        </div>
                        @empty
                        @endforelse
                        <span id="extra"></span>
                        <div class="row">
                            <div class="form-group col-md-12">
                                <input type="button" class="btn btn-success" value="@lang('categories.add_extra')"
                                       onclick="addExtraData()">


                            </div>
                        </div>
                        <hr>
                        <input type="hidden" name="max_extra" id="max_extra">
                        <div class="form-group row mb-0">
                            <div class="col-md-12">
                                <input type="submit" class="btn btn-primary" value="@lang('admin.edit')">
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('styles')
<style type="text/css">
    .select2-selection__rendered {
        line-height: 31px !important;
    }

    .select2-container .select2-selection--single {
        height: 35px !important;
    }

    .select2-selection__arrow {
        height: 34px !important;
    }
</style>
@endsection
@section('scripts')
<script type="text/javascript">
    $(".selected_values").select2({
        tags: true,
        width: '100%'
    });
    var i = '{!! $i !!}';
    i = parseInt(i);

    function addExtraData() {
        i++;
        var html = `
        <div class="row" id="row${i}">
        <input type="hidden" name="extras[${i}][id]" value="0">
        <div class="form-group col-md-4">
        <label class="text-md-right">@lang("categories.title")</label>
        <input type="text" class="form-control" name="extras[${i}][title]" required>
        </div>

        <div class="form-group col-md-3">
        <label class="text-md-right">@lang("categories.type")</label>
        <select class="form-control" name="extras[${i}][type]" id="type${i}" onchange="showValues(${i})" required>
        <option value="text">@lang("categories.text")</option>
        <option value="number">@lang("categories.number")</option>
        <option value="select">@lang("categories.select")</option>

        </select>
        </div>

        <div class="form-group col-md-4" style="display: none" id="values-div${i}">
        <label class="text-md-right">@lang("categories.values")</label>
        <select class="form-control selected_values" name="extras[${i}][values][]" multiple></select>
        </div>

        <div class="form-group col-md-1" id="values-div${i}">
        <label class="text-md-right" style="color: #fff">delete</label>
            <input type="button" class="btn btn-danger" onclick="removeRow(${i})" value="@lang('admin.delete')">
        </div>

        </div>`;

        $('#extra').before(html);
        $('#max_extra').val(i);
        $(".selected_values").select2({
            tags: true,
            width: '100%'
        });
        $('[data-toggle="tooltip"]').tooltip();
    }

    function removeRow(i, url) {
        swal({
            title: '{!! trans('admin.are_you_sure') !!}',
            type: "warning",
            confirmButtonClass: "btn-danger",
            confirmButtonText: "{!! trans('admin.yes'); !!}",
            cancelButtonText: "{!! trans('admin.no'); !!}",
            showCancelButton: true,
            closeOnConfirm: false,
            showLoaderOnConfirm: true
    }, function () {


            $('#row'+i).fadeOut(500).remove();

            if (typeof url != 'undefined') {
                //alert(url); return;
                $.ajax({
                    url: url,
                    type: 'POST',
                    dataType: 'JSON',
                    data: {_token: '{!! csrf_token() !!}', _method : 'delete' }
                }).done(function() {
                    swal({title: "{!! trans('admin.done') !!}", text: "{!! trans('admin.deleted_successfully') !!}", type: "success"});
                }).fail(function(e) {
                    console.log(e);
                    swal("{!! trans('admin.fail') !!}",e.responseJSON.message, "error")
                })
            } else {
                swal.close()
            }
            });




    }

    function showValues(s) {
        if ($('#type' + s).val() == 'select')
            $('#values-div' + s).fadeIn(500).show();
        else
            $('#values-div' + s).fadeOut(500).hide();
    }
</script>
@endsection

resources/views/admin/categories/show.blade.php
@extends('layouts.app')

@section('title','')

@section('content')

    <h1>show page</h1>

@endsection